import { Inter, Concert_One, Eczar } from 'next/font/google'
import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
const inter = Eczar({ subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  )
}
